/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cricketscorecard;

/**
 *
 * @author DELL
 */
public class newMatchJFrame extends javax.swing.JFrame {

    /**
     * Creates new form newMatchJFrame
     */
    public newMatchJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        teamAjLabel = new javax.swing.JLabel();
        teamBjLabel = new javax.swing.JLabel();
        teamNameAjTextField = new javax.swing.JTextField();
        teamNameBjTextField = new javax.swing.JTextField();
        overNumberjLabel = new javax.swing.JLabel();
        overNumberjTextField = new javax.swing.JTextField();
        nextjButton = new javax.swing.JButton();
        newMatchjMenuBar = new javax.swing.JMenuBar();
        homejMenu = new javax.swing.JMenu();

        jLabel1.setText("Enter Int Value in Overs!!");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        teamAjLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        teamAjLabel.setText("Team A Name");

        teamBjLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        teamBjLabel.setText("Team B Name");

        teamNameAjTextField.setText("name");
        teamNameAjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamNameAjTextFieldActionPerformed(evt);
            }
        });

        teamNameBjTextField.setText("name");
        teamNameBjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamNameBjTextFieldActionPerformed(evt);
            }
        });

        overNumberjLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        overNumberjLabel.setText("Number of Over's");

        overNumberjTextField.setText("int value Only");
        overNumberjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overNumberjTextFieldActionPerformed(evt);
            }
        });

        nextjButton.setText("Next");
        nextjButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextjButtonMouseClicked(evt);
            }
        });
        nextjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextjButtonActionPerformed(evt);
            }
        });

        homejMenu.setText("Home");
        homejMenu.setName("hame"); // NOI18N
        newMatchjMenuBar.add(homejMenu);

        setJMenuBar(newMatchjMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nextjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(teamAjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(teamBjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(overNumberjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(teamNameBjTextField)
                            .addComponent(teamNameAjTextField)
                            .addComponent(overNumberjTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(teamAjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(teamNameAjTextField))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teamNameBjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teamBjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(overNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(overNumberjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(nextjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teamNameBjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamNameBjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teamNameBjTextFieldActionPerformed

    private void overNumberjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overNumberjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_overNumberjTextFieldActionPerformed

    private void nextjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextjButtonActionPerformed
        
    }//GEN-LAST:event_nextjButtonActionPerformed

    private void teamNameAjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamNameAjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teamNameAjTextFieldActionPerformed

    private void nextjButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextjButtonMouseClicked
       String teamnameA,teamnameB;
       int over;
       teamnameA= teamNameAjTextField.getText();
       teamnameB= teamNameBjTextField.getText();
       String temp_over= overNumberjTextField.getText();
       over = Integer.parseInt(temp_over);
       teamsName obj = new teamsName(teamnameA, teamnameB, over);
       
       teamAPlayers frame2 = new teamAPlayers();
       frame2.show();
       dispose();
    }//GEN-LAST:event_nextjButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newMatchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newMatchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newMatchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newMatchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newMatchJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu homejMenu;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar newMatchjMenuBar;
    private static javax.swing.JButton nextjButton;
    private javax.swing.JLabel overNumberjLabel;
    private static javax.swing.JTextField overNumberjTextField;
    private javax.swing.JLabel teamAjLabel;
    private javax.swing.JLabel teamBjLabel;
    private static javax.swing.JTextField teamNameAjTextField;
    private static javax.swing.JTextField teamNameBjTextField;
    // End of variables declaration//GEN-END:variables
}
