/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cricketscorecard;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author sai
 */
public class secondInnings extends javax.swing.JFrame {

    static boolean StrikePlayer = true;
    static int bowlcount = 0;
    static boolean CurrentOverRun = false;
    /**
     * Creates new form secondInnings
     */
    public secondInnings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seocndInnings = new javax.swing.JPanel();
        curBat1 = new javax.swing.JLabel();
        curBat2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        runsjLabel = new javax.swing.JLabel();
        bowlsjLabel = new javax.swing.JLabel();
        fourjLabel = new javax.swing.JLabel();
        sixjLabel = new javax.swing.JLabel();
        strikeRatejLabel = new javax.swing.JLabel();
        curBat1Runs = new javax.swing.JLabel();
        curBat1Bowls = new javax.swing.JLabel();
        curBat1fours = new javax.swing.JLabel();
        curBat1sixs = new javax.swing.JLabel();
        curBat1StrikeRate = new javax.swing.JLabel();
        curBat2Runs = new javax.swing.JLabel();
        curBat2Bowls = new javax.swing.JLabel();
        curBat2Fours = new javax.swing.JLabel();
        curBat2Sixs = new javax.swing.JLabel();
        curBat2StrikeRate = new javax.swing.JLabel();
        bowlerjLabel = new javax.swing.JLabel();
        currentBowler = new javax.swing.JLabel();
        curBowlerOver = new javax.swing.JLabel();
        curBowlerRun = new javax.swing.JLabel();
        curBowlerMaidens = new javax.swing.JLabel();
        curBowlerWickets = new javax.swing.JLabel();
        curBowlerEconomy = new javax.swing.JLabel();
        curBat2Runs2 = new javax.swing.JLabel();
        curBat2Bowls2 = new javax.swing.JLabel();
        curBat2Fours2 = new javax.swing.JLabel();
        curBat2Sixs2 = new javax.swing.JLabel();
        curBat2StrikeRate3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        Score = new javax.swing.JLabel();
        battingTeamName = new javax.swing.JLabel();
        currentScore = new javax.swing.JLabel();
        overFinished = new javax.swing.JLabel();
        zeroRun = new javax.swing.JButton();
        oneRun = new javax.swing.JButton();
        twoRun = new javax.swing.JButton();
        threeRun = new javax.swing.JButton();
        fourRun = new javax.swing.JButton();
        sixRun = new javax.swing.JButton();
        wicket = new javax.swing.JButton();
        noBall = new javax.swing.JButton();
        wide = new javax.swing.JButton();
        bye = new javax.swing.JButton();
        legBye = new javax.swing.JButton();
        CustomScore = new javax.swing.JButton();
        changeBatStrike = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ReqRunRate = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        curRunRate = new javax.swing.JLabel();
        selectBat = new javax.swing.JButton();
        selectBowler = new javax.swing.JButton();
        totalOvers = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        totalwickets = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        targetScore = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        seocndInnings.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                seocndInningsKeyPressed(evt);
            }
        });

        curBat1.setText("currentBatsmen1");

        curBat2.setText("currentBatsmen2");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Batsmen");

        runsjLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        runsjLabel.setText("Runs");

        bowlsjLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bowlsjLabel.setText("Bowls");

        fourjLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fourjLabel.setText("4's");

        sixjLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sixjLabel.setText("6's");

        strikeRatejLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        strikeRatejLabel.setText("S.R");

        curBat1Runs.setText("0");

        curBat1Bowls.setText("0");

        curBat1fours.setText("0");

        curBat1sixs.setText("0");

        curBat1StrikeRate.setText("0.0");

        curBat2Runs.setText("0");

        curBat2Bowls.setText("0");

        curBat2Fours.setText("0");

        curBat2Sixs.setText("0");

        curBat2StrikeRate.setText("0.0");

        bowlerjLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bowlerjLabel.setText("Bowlers");

        currentBowler.setText("currentBowler");

        curBowlerOver.setText("0.0");

        curBowlerRun.setText("0");

        curBowlerMaidens.setText("0");

        curBowlerWickets.setText("0");

        curBowlerEconomy.setText("0.0");

        curBat2Runs2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        curBat2Runs2.setText("Overs");

        curBat2Bowls2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        curBat2Bowls2.setText("Runs");

        curBat2Fours2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        curBat2Fours2.setText("M");

        curBat2Sixs2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        curBat2Sixs2.setText("W");

        curBat2StrikeRate3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        curBat2StrikeRate3.setText("Econ");

        Score.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Score.setText("Score");

        battingTeamName.setText("battingTeamName");

        currentScore.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        currentScore.setText("0");

        overFinished.setText("0.0");

        zeroRun.setText("0");
        zeroRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroRunActionPerformed(evt);
            }
        });

        oneRun.setText("1");
        oneRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneRunActionPerformed(evt);
            }
        });

        twoRun.setText("2");
        twoRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoRunActionPerformed(evt);
            }
        });

        threeRun.setText("3");
        threeRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeRunActionPerformed(evt);
            }
        });

        fourRun.setText("4");
        fourRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourRunActionPerformed(evt);
            }
        });

        sixRun.setText("6");
        sixRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixRunActionPerformed(evt);
            }
        });

        wicket.setText("W");
        wicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wicketActionPerformed(evt);
            }
        });

        noBall.setText("Nb");
        noBall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noBallActionPerformed(evt);
            }
        });

        wide.setText("Wd");
        wide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wideActionPerformed(evt);
            }
        });

        bye.setText("Bye");
        bye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byeActionPerformed(evt);
            }
        });

        legBye.setText("L Bye");
        legBye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                legByeActionPerformed(evt);
            }
        });

        CustomScore.setText("Custom");
        CustomScore.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CustomScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomScoreActionPerformed(evt);
            }
        });

        changeBatStrike.setText("Change Batsman's Strike");
        changeBatStrike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBatStrikeActionPerformed(evt);
            }
        });

        jLabel4.setText("Req. Run Rate");

        jLabel6.setText("Current Run Rate");

        curRunRate.setText("0.0");

        selectBat.setText("Select Batsmen");
        selectBat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBatActionPerformed(evt);
            }
        });

        selectBowler.setText("Select Bowler");
        selectBowler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBowlerActionPerformed(evt);
            }
        });

        totalOvers.setText("0.0");

        jLabel2.setText("/");

        jLabel1.setText("/");

        totalwickets.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        totalwickets.setText("0");

        jLabel5.setText("Target Score");

        targetScore.setText("0");

        javax.swing.GroupLayout seocndInningsLayout = new javax.swing.GroupLayout(seocndInnings);
        seocndInnings.setLayout(seocndInningsLayout);
        seocndInningsLayout.setHorizontalGroup(
            seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seocndInningsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(seocndInningsLayout.createSequentialGroup()
                                .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(curBat1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(curBat2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(seocndInningsLayout.createSequentialGroup()
                                        .addComponent(curBat1Runs, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(curBat1Bowls, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(curBat1fours, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(curBat1sixs, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(curBat1StrikeRate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(seocndInningsLayout.createSequentialGroup()
                                        .addComponent(curBat2Runs, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(curBat2Bowls, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(curBat2Fours, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(curBat2Sixs, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(curBat2StrikeRate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(selectBat)
                                            .addComponent(changeBatStrike)))
                                    .addGroup(seocndInningsLayout.createSequentialGroup()
                                        .addComponent(runsjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bowlsjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fourjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sixjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(strikeRatejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(seocndInningsLayout.createSequentialGroup()
                                .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(seocndInningsLayout.createSequentialGroup()
                                        .addComponent(currentBowler)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(curBowlerOver, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(curBowlerRun, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(curBowlerMaidens, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(curBowlerWickets, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(curBowlerEconomy, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(seocndInningsLayout.createSequentialGroup()
                                        .addGap(107, 107, 107)
                                        .addComponent(curBat2Runs2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(curBat2Bowls2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(curBat2Fours2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(curBat2Sixs2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(curBat2StrikeRate3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(selectBowler))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seocndInningsLayout.createSequentialGroup()
                                .addComponent(Score, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(479, 479, 479))
                            .addGroup(seocndInningsLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(seocndInningsLayout.createSequentialGroup()
                                        .addComponent(bowlerjLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(seocndInningsLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(seocndInningsLayout.createSequentialGroup()
                            .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(seocndInningsLayout.createSequentialGroup()
                                    .addComponent(battingTeamName)
                                    .addGap(27, 27, 27)
                                    .addComponent(currentScore)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(totalwickets, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(seocndInningsLayout.createSequentialGroup()
                                    .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5))
                                    .addGap(55, 55, 55)
                                    .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(targetScore, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(curRunRate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ReqRunRate))))
                            .addGap(16, 16, 16)
                            .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(seocndInningsLayout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(CustomScore))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seocndInningsLayout.createSequentialGroup()
                                    .addComponent(overFinished)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(totalOvers)))
                            .addGap(18, 18, 18)
                            .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(seocndInningsLayout.createSequentialGroup()
                                    .addComponent(zeroRun)
                                    .addGap(18, 18, 18)
                                    .addComponent(oneRun)
                                    .addGap(18, 18, 18)
                                    .addComponent(twoRun))
                                .addGroup(seocndInningsLayout.createSequentialGroup()
                                    .addComponent(threeRun)
                                    .addGap(18, 18, 18)
                                    .addComponent(fourRun)
                                    .addGap(18, 18, 18)
                                    .addComponent(sixRun))
                                .addGroup(seocndInningsLayout.createSequentialGroup()
                                    .addComponent(wicket)
                                    .addGap(18, 18, 18)
                                    .addComponent(legBye, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(wide, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(noBall, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(bye, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        seocndInningsLayout.setVerticalGroup(
            seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seocndInningsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(runsjLabel)
                    .addComponent(bowlsjLabel)
                    .addComponent(fourjLabel)
                    .addComponent(sixjLabel)
                    .addComponent(strikeRatejLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(seocndInningsLayout.createSequentialGroup()
                        .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(curBat1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(curBat1Runs)
                            .addComponent(curBat1Bowls)
                            .addComponent(curBat1fours)
                            .addComponent(curBat1sixs)
                            .addComponent(curBat1StrikeRate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(curBat2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(curBat2Runs)
                            .addComponent(curBat2Bowls)
                            .addComponent(curBat2Fours)
                            .addComponent(curBat2Sixs)
                            .addComponent(curBat2StrikeRate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bowlerjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(seocndInningsLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(seocndInningsLayout.createSequentialGroup()
                        .addComponent(selectBat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(changeBatStrike)))
                .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seocndInningsLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(curBat2Runs2)
                            .addComponent(curBat2Bowls2)
                            .addComponent(curBat2Fours2)
                            .addComponent(curBat2Sixs2)
                            .addComponent(curBat2StrikeRate3))
                        .addGap(7, 7, 7)
                        .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(currentBowler, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(curBowlerOver)
                            .addComponent(curBowlerRun)
                            .addComponent(curBowlerMaidens)
                            .addComponent(curBowlerWickets)
                            .addComponent(curBowlerEconomy))
                        .addGap(23, 23, 23))
                    .addGroup(seocndInningsLayout.createSequentialGroup()
                        .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(seocndInningsLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(Score))
                            .addGroup(seocndInningsLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(selectBowler)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(battingTeamName)
                    .addComponent(currentScore)
                    .addComponent(overFinished)
                    .addComponent(jLabel2)
                    .addComponent(totalOvers)
                    .addComponent(jLabel1)
                    .addComponent(totalwickets))
                .addGap(22, 22, 22)
                .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(seocndInningsLayout.createSequentialGroup()
                        .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(seocndInningsLayout.createSequentialGroup()
                                .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(zeroRun)
                                    .addComponent(oneRun)
                                    .addComponent(twoRun)
                                    .addComponent(wide))
                                .addGap(18, 18, 18)
                                .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(threeRun)
                                    .addComponent(fourRun)
                                    .addComponent(sixRun)
                                    .addComponent(noBall)))
                            .addComponent(CustomScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wicket)
                            .addComponent(bye)
                            .addComponent(legBye)))
                    .addGroup(seocndInningsLayout.createSequentialGroup()
                        .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ReqRunRate))
                        .addGap(10, 10, 10)
                        .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(curRunRate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(seocndInningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(targetScore))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Home");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seocndInnings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seocndInnings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zeroRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroRunActionPerformed
        batScoreUpdate2 bsDot = new batScoreUpdate2(StrikePlayer,0);
        bowlerStatUpdate2 one = new bowlerStatUpdate2(true, 0, false);
        scoreUpdate2 sc = new scoreUpdate2(0,1);
    }//GEN-LAST:event_zeroRunActionPerformed

    private void oneRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneRunActionPerformed
        batScoreUpdate2 bsOne = new batScoreUpdate2(StrikePlayer,1);
        bowlerStatUpdate2 one = new bowlerStatUpdate2(true, 1, false);
        scoreUpdate2 sc1 = new scoreUpdate2(1,1);
        strikeUpdate2.strikeUpdate2(1);
    }//GEN-LAST:event_oneRunActionPerformed

    private void twoRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoRunActionPerformed
        batScoreUpdate2 bsTwo = new batScoreUpdate2(StrikePlayer,2);
        bowlerStatUpdate2 one = new bowlerStatUpdate2(true, 2, false);
        scoreUpdate2 scTwo = new scoreUpdate2(2,1);
    }//GEN-LAST:event_twoRunActionPerformed

    private void threeRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeRunActionPerformed
        batScoreUpdate2 bsThree = new batScoreUpdate2(StrikePlayer,3);
        bowlerStatUpdate2 one = new bowlerStatUpdate2(true, 3, false);
        scoreUpdate2 sc3 = new scoreUpdate2(3,1);
        strikeUpdate2.strikeUpdate2(3);
    }//GEN-LAST:event_threeRunActionPerformed

    private void fourRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourRunActionPerformed
        batScoreUpdate2 bsFour = new batScoreUpdate2(StrikePlayer,4);
        bowlerStatUpdate2 one = new bowlerStatUpdate2(true, 4, false);
        scoreUpdate2 sc2 = new scoreUpdate2(4,1);
    }//GEN-LAST:event_fourRunActionPerformed

    private void sixRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixRunActionPerformed
        batScoreUpdate2 bsSix = new batScoreUpdate2(StrikePlayer,6);
        bowlerStatUpdate2 one = new bowlerStatUpdate2(true, 6, false);
        scoreUpdate2 scSix = new scoreUpdate2(6,1);
    }//GEN-LAST:event_sixRunActionPerformed

    private void wicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wicketActionPerformed
        batScoreUpdate2 bsOut = new batScoreUpdate2(StrikePlayer,0);
        bowlerStatUpdate2 one = new bowlerStatUpdate2(true, 0, true);
        scoreUpdate2 scW = new scoreUpdate2(0,1);
        batsmenOut2.batsmenOut2(StrikePlayer);
        secondInnings.totalwickets.setText(String.valueOf((Integer.parseInt(secondInnings.totalwickets.getText())+1)));

    }//GEN-LAST:event_wicketActionPerformed

    private void noBallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noBallActionPerformed
        int custom = Integer.parseInt(JOptionPane.showInputDialog("Enter Runs!"));
        batScoreUpdate2 bsNB = new batScoreUpdate2(StrikePlayer,custom);
        bowlerStatUpdate2 one = new bowlerStatUpdate2(false, custom+1, false);
        scoreUpdate2 scNB = new scoreUpdate2(custom+1,0);
        strikeUpdate2.strikeUpdate2(custom);
    }//GEN-LAST:event_noBallActionPerformed

    private void wideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wideActionPerformed
        int custom = Integer.parseInt(JOptionPane.showInputDialog("Any Bye's Runs?"));
        bowlerStatUpdate2 one = new bowlerStatUpdate2(false, 1, false);
        scoreUpdate2 scWd = new scoreUpdate2(custom+1,0);
        strikeUpdate2.strikeUpdate2(custom);

    }//GEN-LAST:event_wideActionPerformed

    private void byeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byeActionPerformed
        int custom = Integer.parseInt(JOptionPane.showInputDialog("Enter Runs!"));
        batScoreUpdate2 bsBye = new batScoreUpdate2(StrikePlayer,0);
        bowlerStatUpdate2 one = new bowlerStatUpdate2(true, 0, false);
        scoreUpdate2 scCustom = new scoreUpdate2(custom,1);
        strikeUpdate2.strikeUpdate2(custom);
    }//GEN-LAST:event_byeActionPerformed

    private void legByeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_legByeActionPerformed
        int custom = Integer.parseInt(JOptionPane.showInputDialog("Enter Runs!"));
        batScoreUpdate2 bsLB = new batScoreUpdate2(StrikePlayer,0);
        bowlerStatUpdate2 one = new bowlerStatUpdate2(true, 0, false);
        scoreUpdate2 scCustom = new scoreUpdate2(custom,1);
        strikeUpdate2.strikeUpdate2(custom);
    }//GEN-LAST:event_legByeActionPerformed

    private void CustomScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomScoreActionPerformed
        int custom = Integer.parseInt(JOptionPane.showInputDialog("Enter Runs!"));
        batScoreUpdate2 bsCus = new batScoreUpdate2(StrikePlayer,custom);
        bowlerStatUpdate2 one = new bowlerStatUpdate2(true, custom, false);
        scoreUpdate2 scCustom = new scoreUpdate2(custom,1);
        strikeUpdate2.strikeUpdate2(custom);
    }//GEN-LAST:event_CustomScoreActionPerformed

    private void changeBatStrikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBatStrikeActionPerformed
        if(StrikePlayer){
            StrikePlayer=false;
        }
        else{
            StrikePlayer=true;
        }
    }//GEN-LAST:event_changeBatStrikeActionPerformed

    private void selectBatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBatActionPerformed
        selectBatsmen2 batFrame = new selectBatsmen2();
        batFrame.show();
        dispose();
    }//GEN-LAST:event_selectBatActionPerformed

    private void selectBowlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBowlerActionPerformed
        selectBowler2 framed = new selectBowler2();
        framed.setVisible(true);
        //        dispose();
    }//GEN-LAST:event_selectBowlerActionPerformed

    private void seocndInningsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_seocndInningsKeyPressed
        int code = evt.getKeyCode();
        if(KeyEvent.VK_4 == code){
            fourRun.doClick();
        }
        System.out.println(evt.getKeyChar());
    }//GEN-LAST:event_seocndInningsKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        curBat1.setText(selectBatsmen2.CurBat1);
        curBat2.setText(selectBatsmen2.CurBat2);
        if(firstInningBat.batTeam2.equals("teama")){
            battingTeamName.setText(teamsName.getTeamA());
        }else{
            battingTeamName.setText(teamsName.getTeamB());
        }
        totalOvers.setText(String.valueOf(teamsName.getOvers()));
        targetScore.setText(String.valueOf(Integer.parseInt(firstInningsJFrame.currentScore.getText())+1));
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(secondInnings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(secondInnings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(secondInnings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(secondInnings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new secondInnings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CustomScore;
    public static javax.swing.JLabel ReqRunRate;
    private javax.swing.JLabel Score;
    public static javax.swing.JLabel battingTeamName;
    private javax.swing.JLabel bowlerjLabel;
    private javax.swing.JLabel bowlsjLabel;
    private javax.swing.JButton bye;
    public static javax.swing.JButton changeBatStrike;
    public static javax.swing.JLabel curBat1;
    public static javax.swing.JLabel curBat1Bowls;
    public static javax.swing.JLabel curBat1Runs;
    public static javax.swing.JLabel curBat1StrikeRate;
    public static javax.swing.JLabel curBat1fours;
    public static javax.swing.JLabel curBat1sixs;
    public static javax.swing.JLabel curBat2;
    public static javax.swing.JLabel curBat2Bowls;
    private javax.swing.JLabel curBat2Bowls2;
    public static javax.swing.JLabel curBat2Fours;
    private javax.swing.JLabel curBat2Fours2;
    public static javax.swing.JLabel curBat2Runs;
    private javax.swing.JLabel curBat2Runs2;
    public static javax.swing.JLabel curBat2Sixs;
    private javax.swing.JLabel curBat2Sixs2;
    public static javax.swing.JLabel curBat2StrikeRate;
    private javax.swing.JLabel curBat2StrikeRate3;
    public static javax.swing.JLabel curBowlerEconomy;
    public static javax.swing.JLabel curBowlerMaidens;
    public static javax.swing.JLabel curBowlerOver;
    public static javax.swing.JLabel curBowlerRun;
    public static javax.swing.JLabel curBowlerWickets;
    public static javax.swing.JLabel curRunRate;
    public static javax.swing.JLabel currentBowler;
    public static javax.swing.JLabel currentScore;
    private javax.swing.JButton fourRun;
    private javax.swing.JLabel fourjLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton legBye;
    private javax.swing.JButton noBall;
    private javax.swing.JButton oneRun;
    public static javax.swing.JLabel overFinished;
    private javax.swing.JLabel runsjLabel;
    public static javax.swing.JButton selectBat;
    public static javax.swing.JButton selectBowler;
    public static javax.swing.JPanel seocndInnings;
    private javax.swing.JButton sixRun;
    private javax.swing.JLabel sixjLabel;
    private javax.swing.JLabel strikeRatejLabel;
    public static javax.swing.JLabel targetScore;
    private javax.swing.JButton threeRun;
    public static javax.swing.JLabel totalOvers;
    public static javax.swing.JLabel totalwickets;
    private javax.swing.JButton twoRun;
    private javax.swing.JButton wicket;
    private javax.swing.JButton wide;
    private javax.swing.JButton zeroRun;
    // End of variables declaration//GEN-END:variables
}
