/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cricketscorecard;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;


/**
 *
 * @author DELL
 */
public class teamAPlayers extends javax.swing.JFrame {
    int UId = 1;
    /**
     * Creates new form teamAPlayers
     */
    public teamAPlayers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teamAplayersjPanel = new javax.swing.JPanel();
        teamAnamejLabel = new javax.swing.JLabel();
        playernamejLabel = new javax.swing.JLabel();
        playerNameTeamAjTextField = new javax.swing.JTextField();
        jScrollPanel = new javax.swing.JScrollPane();
        teamAjTable = new javax.swing.JTable();
        addjButton = new javax.swing.JButton();
        nextjButton = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        teamAnamejLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        teamAnamejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teamAnamejLabel.setText("Team A Name");
        teamAnamejLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        playernamejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playernamejLabel.setText("Player Name");
        playernamejLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        playerNameTeamAjTextField.setText("Player Name");

        teamAjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Player ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPanel.setViewportView(teamAjTable);

        addjButton.setText("Add");
        addjButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addjButtonMouseClicked(evt);
            }
        });
        addjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButtonActionPerformed(evt);
            }
        });

        nextjButton.setText("Next");
        nextjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout teamAplayersjPanelLayout = new javax.swing.GroupLayout(teamAplayersjPanel);
        teamAplayersjPanel.setLayout(teamAplayersjPanelLayout);
        teamAplayersjPanelLayout.setHorizontalGroup(
            teamAplayersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teamAplayersjPanelLayout.createSequentialGroup()
                .addGroup(teamAplayersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, teamAplayersjPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, teamAplayersjPanelLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(teamAnamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, teamAplayersjPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(playernamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(playerNameTeamAjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(teamAplayersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nextjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        teamAplayersjPanelLayout.setVerticalGroup(
            teamAplayersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teamAplayersjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teamAnamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(teamAplayersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(teamAplayersjPanelLayout.createSequentialGroup()
                        .addGroup(teamAplayersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(playernamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playerNameTeamAjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(teamAplayersjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nextjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(teamAplayersjPanelLayout.createSequentialGroup()
                        .addComponent(addjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jMenu1.setText("Home");
        jMenuBar.add(jMenu1);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teamAplayersjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teamAplayersjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextjButtonActionPerformed
                DefaultTableModel teamAP1 = (DefaultTableModel)teamAjTable.getModel();
                if(teamAP1.getRowCount()==0){
                    JOptionPane.showMessageDialog(this,"Table is Empty");
                }else{
                    String PlayerID,PlayerName;
                    if(UId<11){
                        JOptionPane.showMessageDialog(this,"Insert 11 Players!");
                    }else{
                    try{
                        Class.forName("oracle.jdbc.OracleDriver");
                        java.sql.Connection cn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","oracle");
                        for(int i=0;i<teamAP1.getRowCount();i++){
                            PlayerID = teamAP1.getValueAt(i,0).toString();
                            PlayerName = teamAP1.getValueAt(i, 1).toString();
                                                        
                            String teamAQuery = "INSERT INTO TEAMA(PlayerID,PlayerName)VALUES(?,?)";
                            PreparedStatement teamAStat = cn.prepareStatement(teamAQuery);
                            teamAStat.setString(1,PlayerID);
                            teamAStat.setString(2,PlayerName);
                            teamAStat.execute();
                        }
                        JOptionPane.showMessageDialog(this,"Data Inserted Successfully!");
                        teamAP1.setRowCount(0);
                    }catch(Exception e){
                        System.out.println("Error Occured");
                         e.printStackTrace();
                    }

                    teamBPlayers frame3 = new teamBPlayers();
                    frame3.show();
                    dispose();
                    }
    }//GEN-LAST:event_nextjButtonActionPerformed
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
                teamAnamejLabel.setText((teamsName.getTeamA()));            
    }//GEN-LAST:event_formWindowOpened

    private void addjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addjButtonActionPerformed

    private void addjButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addjButtonMouseClicked
         //Have to Differ in every team making for primary key.   
         if(UId==12){
             JOptionPane.showMessageDialog(this,"Already 11 Players Inserted!");
         }
         else{
            if (playerNameTeamAjTextField.getText().equals("")) {
                    JOptionPane.showMessageDialog(this,"Please fill data in field");
            }else{
                    String data[] ={Integer.toString(UId++),playerNameTeamAjTextField.getText()};
                    
                    DefaultTableModel teamAP = (DefaultTableModel)teamAjTable.getModel();
                    teamAP.addRow(data);
                    JOptionPane.showMessageDialog(this," Data inserted succesfully");
                    playerNameTeamAjTextField.setText("");
                }
            }
    }//GEN-LAST:event_addjButtonMouseClicked
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teamAPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teamAPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teamAPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teamAPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teamAPlayers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addjButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JScrollPane jScrollPanel;
    private javax.swing.JButton nextjButton;
    private javax.swing.JTextField playerNameTeamAjTextField;
    private javax.swing.JLabel playernamejLabel;
    private javax.swing.JTable teamAjTable;
    private static javax.swing.JLabel teamAnamejLabel;
    private javax.swing.JPanel teamAplayersjPanel;
    // End of variables declaration//GEN-END:variables
}
