/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cricketscorecard;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.*;

/**
 *
 * @author DELL
 */
public class teamBPlayers extends javax.swing.JFrame {

    int UID = 12;
    /**
     * Creates new form teamBPlayers
     */
    public teamBPlayers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teamBPlayerjPanel = new javax.swing.JPanel();
        teamBNamejLabel = new javax.swing.JLabel();
        playerBjTextField = new javax.swing.JTextField();
        playerNamejLabel = new javax.swing.JLabel();
        addjButton = new javax.swing.JButton();
        nextjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        teamBjTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        teamBNamejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teamBNamejLabel.setText("Team B Name");
        teamBNamejLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        playerBjTextField.setText("Player Name");
        playerBjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerBjTextFieldActionPerformed(evt);
            }
        });

        playerNamejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerNamejLabel.setText("Player Name");
        playerNamejLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        addjButton.setText("Add");
        addjButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addjButtonMouseClicked(evt);
            }
        });

        nextjButton.setText("Next");
        nextjButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextjButtonMouseClicked(evt);
            }
        });
        nextjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextjButtonActionPerformed(evt);
            }
        });

        teamBjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Player ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(teamBjTable);

        javax.swing.GroupLayout teamBPlayerjPanelLayout = new javax.swing.GroupLayout(teamBPlayerjPanel);
        teamBPlayerjPanel.setLayout(teamBPlayerjPanelLayout);
        teamBPlayerjPanelLayout.setHorizontalGroup(
            teamBPlayerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teamBPlayerjPanelLayout.createSequentialGroup()
                .addGroup(teamBPlayerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, teamBPlayerjPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, teamBPlayerjPanelLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(teamBNamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, teamBPlayerjPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(playerNamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(playerBjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(teamBPlayerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nextjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        teamBPlayerjPanelLayout.setVerticalGroup(
            teamBPlayerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teamBPlayerjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teamBNamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(teamBPlayerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(teamBPlayerjPanelLayout.createSequentialGroup()
                        .addGroup(teamBPlayerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(playerNamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playerBjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(teamBPlayerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nextjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(teamBPlayerjPanelLayout.createSequentialGroup()
                        .addComponent(addjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jMenu1.setText("Home");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(teamBPlayerjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(teamBPlayerjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextjButtonActionPerformed

    private void playerBjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerBjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerBjTextFieldActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        teamBNamejLabel.setText((teamsName.getTeamB()));
    }//GEN-LAST:event_formWindowOpened

    private void addjButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addjButtonMouseClicked
        if(UID<23){
            if(playerBjTextField.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please Fill Data in Field");
        }else{
            String Data1[] = {Integer.toString(UID++),playerBjTextField.getText()};
            DefaultTableModel teamBP = (DefaultTableModel)teamBjTable.getModel();
            teamBP.addRow(Data1);
            JOptionPane.showMessageDialog(this,"Data Inserted Successfully");
            playerBjTextField.setText("");
        }
        }else{
            JOptionPane.showMessageDialog(this,"Already 11 Players Inserted!");
        }
    }//GEN-LAST:event_addjButtonMouseClicked

    private void nextjButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextjButtonMouseClicked
             if(UID<23){
                JOptionPane.showMessageDialog(this,"Insert 11 Players!");
            }else{
            DefaultTableModel teamBP = (DefaultTableModel) teamBjTable.getModel();
            if(teamBP.getRowCount()==0){
                JOptionPane.showMessageDialog(this,"Table is Empty!");
            }else{
                String PlayerID,PlayerName;
                try{
                    Class.forName("oracle.jdbc.OracleDriver");
                    Connection cn2 = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","oracle");
                    for(int i=0;i<teamBP.getRowCount();i++){
                        PlayerID = teamBP.getValueAt(i,0).toString();
                        PlayerName = teamBP.getValueAt(i, 1).toString();
                        
                        String teamBQuery = "INSERT INTO TEAMB(PlayerID,PlayerName)VALUES(?,?)";
                        PreparedStatement teamBStat = cn2.prepareStatement(teamBQuery);
                        teamBStat.setString(1, PlayerID);
                        teamBStat.setString(2, PlayerName);
                        teamBStat.execute();
                    }
                     JOptionPane.showMessageDialog(this,"Data Inserted Successfully!");
                     teamBP.setRowCount(0);
                     
                }catch(Exception e){
                    System.out.println("Error Occured");
                    e.printStackTrace();
                }                
            matchTossJFrame frame4 = new matchTossJFrame();
            frame4.show();
            dispose();            
            }     
            }                        
    }//GEN-LAST:event_nextjButtonMouseClicked
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teamBPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teamBPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teamBPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teamBPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teamBPlayers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addjButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextjButton;
    private javax.swing.JTextField playerBjTextField;
    private javax.swing.JLabel playerNamejLabel;
    private javax.swing.JLabel teamBNamejLabel;
    private javax.swing.JPanel teamBPlayerjPanel;
    private javax.swing.JTable teamBjTable;
    // End of variables declaration//GEN-END:variables
}
